// Authentication system using Supabase
import { supabase } from "@/integrations/supabase/client";

export interface User {
  id: string;
  email: string;
  full_name: string;
  created_at: string;
  user_type?: 'sending' | 'receiving'; // odosielajúci lekár / prijímajúci lekár
  ambulance_code?: string;
}

export interface Session {
  user: User;
  token: string;
}

export const auth = {
  async signUp(email: string, password: string, fullName: string, userType?: 'sending' | 'receiving'): Promise<Session> {
    // Note: ambulance_code is automatically generated by database trigger
    // based on full_name, so we don't need to generate it here
    
    // Sign up with Supabase Auth
    const { data: authData, error: authError } = await supabase.auth.signUp({
      email,
      password,
      options: {
        data: {
          full_name: fullName,
          user_type: userType,
        }
      }
    });

    if (authError) {
      throw new Error(authError.message);
    }

    if (!authData.user) {
      throw new Error('Registrácia zlyhala');
    }

    // Note: Profile is automatically created by database trigger (handle_new_user)
    // No need to manually create it here

    // Get profile to fetch the auto-generated ambulance_code
    const { data: profile } = await supabase
      .from('profiles')
      .select('ambulance_code')
      .eq('id', authData.user.id)
      .maybeSingle(); // Use maybeSingle() to handle missing profiles gracefully

    // Return session
    const session: Session = {
      user: {
        id: authData.user.id,
        email: authData.user.email!,
        full_name: fullName,
        created_at: authData.user.created_at,
        user_type: userType,
        ambulance_code: profile?.ambulance_code || '',
      },
      token: authData.session?.access_token || '',
    };

    return session;
  },

  async signIn(email: string, password: string): Promise<Session> {
    // Sign in with Supabase Auth
    const { data: authData, error: authError } = await supabase.auth.signInWithPassword({
      email,
      password,
    });

    if (authError) {
      throw new Error('Nesprávny email alebo heslo');
    }

    if (!authData.user || !authData.session) {
      throw new Error('Prihlásenie zlyhalo');
    }

    // Get user profile
    const { data: profile } = await supabase
      .from('profiles')
      .select('*')
      .eq('id', authData.user.id)
      .maybeSingle(); // Use maybeSingle() to handle missing profiles gracefully

    // Return session
    const session: Session = {
      user: {
        id: authData.user.id,
        email: authData.user.email!,
        full_name: profile?.full_name || authData.user.email!,
        created_at: authData.user.created_at,
        user_type: profile?.user_type,
        ambulance_code: profile?.ambulance_code,
      },
      token: authData.session.access_token,
    };

    return session;
  },

  async signOut(): Promise<void> {
    await supabase.auth.signOut();
  },

  async getSession(): Promise<Session | null> {
    const { data: { session } } = await supabase.auth.getSession();
    
    if (!session) return null;

    // Get user profile
    let { data: profile } = await supabase
      .from('profiles')
      .select('*')
      .eq('id', session.user.id)
      .maybeSingle(); // Use maybeSingle() to handle missing profiles gracefully

    // If profile doesn't exist, try to create it automatically
    if (!profile) {
      console.warn('Profile not found for user, attempting to create:', session.user.id);
      
      // Try to get user metadata from auth
      const userMetadata = session.user.user_metadata || {};
      const fullName = userMetadata.full_name || session.user.email?.split('@')[0] || 'User';
      const userType = userMetadata.user_type || 'sending';

      // Attempt to create profile
      const { data: newProfile, error: createError } = await supabase
        .from('profiles')
        .insert({
          id: session.user.id,
          email: session.user.email!,
          full_name: fullName,
          user_type: userType,
        })
        .select()
        .maybeSingle();

      if (createError) {
        console.error('Failed to create profile automatically:', createError);
        // Continue without profile - user can create it manually in ProfileSettings
      } else {
        profile = newProfile;
        console.log('Profile created automatically:', profile);
      }
    }

    return {
      user: {
        id: session.user.id,
        email: session.user.email!,
        full_name: profile?.full_name || session.user.email!,
        created_at: session.user.created_at,
        user_type: profile?.user_type,
        ambulance_code: profile?.ambulance_code,
      },
      token: session.access_token,
    };
  },

  async getCurrentUser(): Promise<User | null> {
    const session = await this.getSession();
    return session?.user || null;
  },
};
